name: micro_core_logger
description: This is a simple package to log formatted messages on terminal easily with colors.
version: 0.1.0
repository: https://github.com/JotaPe-Tecnologia/micro-core-logger
issue_tracker: https://github.com/JotaPe-Tecnologia/micro-core-logger/issues
homepage: https://www.jotapetecnologia.com.br/flutter/packages/micro_core_logger

environment:
  sdk: ^3.2.6

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.0
