name: easy_logs
description: This is a simple package to log formatted messages on terminal easily with colors.
version: 0.0.1
repository: https://github.com/JotaPe-Tecnologia/easy-logs
issue_tracker: https://github.com/JotaPe-Tecnologia/easy-logs/issues
homepage: https://www.jotapetecnologia.com.br/flutter/packages/easy_logs

environment:
  sdk: ^3.2.6

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.0
